### ISSUE TITLE
allow NewRootCmd to receive an option to set Viper Prefix

### ISSUE THREAD

**Issue by jhernandezb** [tendermint/spm#17]
Currently the viper prefix is used for environment variables, this is useful if you need to deal with different networks for example
```
GAIA_NODE=http://gaia:26657
STARGAZE_NODE=http://stargaze:26657
```

This will require a small change in `WithViper` to accept an option
```go
	initClientCtx := client.Context{}.
		WithCodec(encodingConfig.Marshaler).
		WithInterfaceRegistry(encodingConfig.InterfaceRegistry).
		WithTxConfig(encodingConfig.TxConfig).
		WithLegacyAmino(encodingConfig.Amino).
		WithInput(os.Stdin).
		WithAccountRetriever(types.AccountRetriever{}).
		WithBroadcastMode(flags.BroadcastBlock).
		WithHomeDir(defaultNodeHome).
		WithViper("")
```

**Comment by Pantani** [comment]
Nice idea!
We can add the `WithEnvPrefix` option with a vanilla implementation instead of adding viper only to do this. What do you think @ilgooz, @lubtd, @ivanovpetr, and @fadeev?

**Comment by ilgooz** [comment]
Ofc, let's do it! 🎊

**Comment by jhernandezb** [comment]
Opened https://github.com/tendermint/spm/pull/23
