### ISSUE TITLE
request release v0.1.8 for supporting cosmos sdk 0.44.3

### ISSUE THREAD

**Issue by fly33499** [tendermint/spm#20]
Hi. thank you for great project.

Recently, I've seen update for sdk v0.44.3 on the spm project.

```
jhernandezb fix(cosmoscmd): home flag parsing in sdk v0.44.3 (#16 
```

Can you release v0.1.8 for starport use? 
I want to upgrade my chain to cosmos v0.44.3. 

@Pantani

**Comment by Pantani** [comment]
@fly33499, thanks for the issue report. We will update in future starport releases. Do you have any special reason to use the `v0.44.3`?

**Comment by fly33499** [comment]
@Pantani Hi. Thank you for reply. I have a plan to launch a public testnet on my chain , so I wanted to apply the latest version in advance before launching. Anyway, I adapted the latest committed spm to inside my chain directly.

I'm going to change it again when spm is updated later.

Thanks a lot!
